---
name: Build Docker Image

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: false
